#pragma config(Motor,  port1,           backRightWheel, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftClawArm,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeftWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftRotate,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           goalLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightRotate,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           frontRightWheel, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           backLeftWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightClawArm,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int X2 = 0, Y1 = 0, X1 = 0,d = 0;
void mecanum_Drive(int threshold, int speed);
void tank_Drive(int threshold, int speed);
int speed();
void driveMode(int choice, int threshold);
//void waitForRelease();
int Choice();
void claw(int pos1, int pos2);
void ClawArm(int threshold);
void backLift(int threshold);
void Rotate(int speed2);

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
int threshold = 10, speed3 = 127;
  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................
claw(speed3,-speed3);
		ClawArm(threshold);
		backLift(threshold);
		Rotate(63);
		driveMode(Choice(), threshold);
  }
}
void mecanum_Drive(int threshold, int speed)
{
	//Create "deadzone" variables. Adjust threshold value to increase/decrease deadzone



	//Create "deadzone" for Y1/Ch3
	if(abs(vexRT[Ch3]) > threshold)
		Y1 = vexRT[Ch3];
	else
		Y1 = 0;
	//Create "deadzone" for X1/Ch4
	if(abs(vexRT[Ch4]) > threshold)
		X1 = vexRT[Ch4];
	else
		X1 = 0;
	//Create "deadzone" for X2/Ch1
	if(abs(vexRT[Ch1]) > threshold)
		X2 = vexRT[Ch1];
	else
		X2 = 0;

	//Remote Control Commands
	motor[frontRightWheel] = (Y1 - X2 - X1)/speed;
	motor[backRightWheel] =  (Y1 - X2 + X1)/speed;
	motor[frontLeftWheel] = (Y1 + X2 + X1)/speed;
	motor[backLeftWheel] =  (Y1 + X2 - X1)/speed;

}
void tank_Drive(int threshold, int speed)
{
	if(abs(vexRT[Ch3]) > threshold)         // If the left joystick is greater than or less than the threshold:
	{
		motor[frontLeftWheel]  = (vexRT[Ch3])/speed;   // Left Joystick Y value / 2.
		motor[backLeftWheel]  = (vexRT[Ch3])/speed;
	}
	else                                    // If the left joystick is within the threshold:
	{
		motor[frontLeftWheel]  = 0;
		motor[backLeftWheel]  = 0;// Stop the left motor (cancel noise)
	}

	if(abs(vexRT[Ch2]) > threshold)         // If the right joystick is greater than or less than the threshold:
	{
		motor[frontRightWheel] = (vexRT[Ch2])/speed;   // Right Joystick Y value / 2.
		motor[backRightWheel] = (vexRT[Ch2])/speed;
	}
	else                                    // If the right joystick is within the threshold:
	{
		motor[frontRightWheel] = 0;
		motor[backRightWheel] = 0;                // Stop the right motor (cancel noise)
	}
}

int speed()
{
	if (vexRT[Btn6U] == 1 )
	{
		return 1;
	}
	else if (vexRT[Btn6D] == 1 )
	{
		return 1;
	}
	else if (vexRT[Btn5U] == 1 )
	{
		return 1;
	}
	else if (vexRT[Btn5D] == 1 )
	{
		return 1;
	}
	else
	{
		return 2;
	}
}

void driveMode(int choice,int threshold)
{
	displayLCDNumber(1, 10, choice, 2);
	if (choice == 1)
	{
		mecanum_Drive(threshold, speed());
	}
	else
	{
		tank_Drive(threshold, speed());
	}
}

int Choice()
{

	if (vexRT[Btn8D] == 1)
		d = 1;
	else if (vexRT[Btn8L] == 1)
		d = 2;
	else
		return d ;

}

//void waitForRelease()
//{
//	while(vexRT[Btn8D] != 0){}
//	wait1Msec(5);
//}

void claw(int pos1, int pos2)
{
	if (vexRT[Btn6UXmtr2] == 1)
	{
		motor[Claw] = pos1;
	}
	else if (vexRT[Btn6DXmtr2] == 1)
	{
		motor[Claw] = pos2;
	}
}

void ClawArm(int threshold)
{
	if(abs(vexRT[Ch2Xmtr2]) > threshold)         // If the right joystick is greater than or less than the threshold:
	{
	motor[leftClawArm] = vexRT[Ch2Xmtr2];
	motor[rightClawArm] = vexRT[Ch2Xmtr2];
	}
	else                                    // If the right joystick is within the threshold:
	{
		motor[leftClawArm] = 0;
		motor[rightClawArm] = 0;                // Stop the right motor (cancel noise)
	}
}

void backLift(int threshold)
{
	if(abs(vexRT[Ch3Xmtr2]) > threshold)         // If the right joystick is greater than or less than the threshold:
	{
	motor[goalLift] = vexRT[Ch3Xmtr2];
	}
	else                                    // If the right joystick is within the threshold:
	{
		motor[goalLift] = 0;               // Stop the right motor (cancel noise)
	}
}

void Rotate(int speed2)
{

	if (vexRT[Btn5UXmtr2] == 1)
	{
		motor[rightRotate] = speed2;
		motor[leftRotate] = speed2;
	}
	else if (vexRT[Btn5DXmtr2] == 1)
	{
		motor[rightRotate] = -speed2;
		motor[leftRotate] = -speed2;
	}
	else
	{
		motor[rightRotate] = 0;
		motor[leftRotate] = 0;
	}
}
